DROP TABLE IF EXISTS sensor;
DROP TABLE IF EXISTS temp_record;

CREATE TABLE sensor (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  path TEXT NOT NULL,
  type TEXT NOT NULL
);

CREATE TABLE temp_record (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sensor_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value DOUBLE NOT NULL,
  trans TEXT NOT NULL,
  FOREIGN KEY (sensor_id) REFERENCES sensor (id)
);